version: '3.2'
services:
     
  eth-node:
    image: kauriorg/parity-docker
    ports:
      - "8545:8545"
    networks:
      - default

  truffle:
    image: gjeanmart/truffle-docker
    ports:
      - "8888:8888"
    volumes:
      - /path/to/truffle/project:/project
    depends_on:
      - eth-node
    environment:
      NETWORK: docker
      API_PORT: 8888
      API_HOST: 0.0.0.0
    networks:
      - default

networks:
  default:
