version: '3.2'
services:
     
  parity:
    image: gjeanmart/parity-dev-docker
    ports:
      - "8545:8545"
    networks:
      - default

  truffle:
    image: gjeanmart/truffle-docker
    ports:
      - "8888:8888"
    volumes:
      - /path/to/truffle/project:/project
    depends_on:
      - parity
    environment:
      ACTION: migrate
      NETWORK: development
      RPC_HOST: parity
      RPC_PORT: 8545
      API_PORT: 8888
      API_HOST: 0.0.0.0
    networks:
      - default

networks:
  default:
